apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
      - mountPath: "/mnt"
        name: stor1
  restartPolicy: Always
  volumes:
    - name: stor1
      persistentVolumeClaim:
        claimName: pvc1
