apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: default
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: stor1
  volumes:
    - name: stor1
      persistentVolumeClaim:
        claimName: pvc1
