apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumen1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs: 
    path: /MVs/NFS
    server: 192.168.39.1
    readOnly: false
